apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-mysql
  labels:
    app: test-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-mysql
  template:
    metadata:
      labels:
        app: test-mysql
    spec:
      containers:
      - image: mysql:8
        name: test-mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: password
          - name: MYSQL_DATABASE
            value: test-db
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: test-mysql
  ports:
    - port: 3306
